[project]
name = "landauer_opt"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = ["qiskit>=1.2", "networkx>=3.2"]

[project.optional-dependencies]
dev = ["pytest", "black", "ruff"]
docs = [
  "mkdocs-material[charts]>=9.5",
  "mkdocstrings[python]>=0.24",
]