name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install package (+dev extras)
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev]'    # ruff, black, pytest

      - name: Lint & style
        run: |
          ruff check .
          black --check .

      - name: Unit tests
        run: pytest -q